version: "3"

services:
  sql-server-db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 5430:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=Customer#2022
    restart: "always"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Customer#2022 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s  
    